version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: ../docker-files/server/Dockerfile
    ports:
      - "5001:5001"
  
  frontend:
    build:
      context: ./client-app
      dockerfile: ../docker-files/client-app/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
