name: ESLint

on: push

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: |
        cd client-app
        npm install
    - name: Lint
      run: |
        cd client-app
        npm run lint
    - name: Format
      run: |
        cd client-app
        npm run format